name: ci
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
          id: yarn cache
          with:
            path: |
              ~/cache
              !~/cache/exclude
              **/node_modules
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-

      - name: Install Dependencies
        uses: yarn install

      - name: Linting
        uses: yarn lint

      - name: Test
        uses: yarn test:ci

      - name: Build
        uses: yarn build
